version: 2
jobs:
  build:
    docker:
      - image: cimg/openjdk:16.0.0

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx1Gm
      TERM: dumb

    steps:
      - checkout
      - run: gradle clean build
